// AUTO-GENERATED by scripts/generate-feature-flags.mjs from features.json
// Do not edit by hand. Re-run via `npm run generate:flags` or any build script.

export type FeatureFlagKey =
  | 'enableClaudeSdk'
  | 'enableCopilotSdk'
  | 'enableExperimentalFeatures'
  | 'prScoresAiReview'
  | 'showAgentSelection'
  | 'showBackstageExplorer'
  | 'showBudgetLimits'
  | 'showClearMemory'
  | 'showComplianceLogs'
  | 'showComposer'
  | 'showConfigure'
  | 'showCostTracking'
  | 'showDashboard'
  | 'showDataManagement'
  | 'showEfficiencyCoach'
  | 'showEnvVars'
  | 'showExtensions'
  | 'showHomeHub'
  | 'showInsights'
  | 'showIntegrations'
  | 'showKnowledgeBase'
  | 'showLearn'
  | 'showMcpServers'
  | 'showMemory'
  | 'showPlugins'
  | 'showPolicies'
  | 'showPrScores'
  | 'showScheduler'
  | 'showSessionWizard'
  | 'showSettings'
  | 'showSetupWizard'
  | 'showSkillsManagement'
  | 'showSubAgents'
  | 'showTeamHub'
  | 'showTemplates'
  | 'showUseContext'
  | 'showVoice'
  | 'showWebhooks'
  | 'showWork'
  | 'showWorkspaces';

export type FeatureFlags = {
  enableClaudeSdk: boolean;
  enableCopilotSdk: boolean;
  enableExperimentalFeatures: boolean;
  prScoresAiReview: boolean;
  showAgentSelection: boolean;
  showBackstageExplorer: boolean;
  showBudgetLimits: boolean;
  showClearMemory: boolean;
  showComplianceLogs: boolean;
  showComposer: boolean;
  showConfigure: boolean;
  showCostTracking: boolean;
  showDashboard: boolean;
  showDataManagement: boolean;
  showEfficiencyCoach: boolean;
  showEnvVars: boolean;
  showExtensions: boolean;
  showHomeHub: boolean;
  showInsights: boolean;
  showIntegrations: boolean;
  showKnowledgeBase: boolean;
  showLearn: boolean;
  showMcpServers: boolean;
  showMemory: boolean;
  showPlugins: boolean;
  showPolicies: boolean;
  showPrScores: boolean;
  showScheduler: boolean;
  showSessionWizard: boolean;
  showSettings: boolean;
  showSetupWizard: boolean;
  showSkillsManagement: boolean;
  showSubAgents: boolean;
  showTeamHub: boolean;
  showTemplates: boolean;
  showUseContext: boolean;
  showVoice: boolean;
  showWebhooks: boolean;
  showWork: boolean;
  showWorkspaces: boolean;
};

export interface FeatureFlagMetadata {
  experimental: boolean;
  enabled: boolean;
  addedIn: string | null;
}

/**
 * Build-time effective values. Experimental flags reflect their
 * `enabled` from features.json unless CLEARPATH_E2E_EXPERIMENTAL=1 is set
 * at generation time, in which case every experimental flag is forced on.
 */
export const BUILD_FLAGS: Readonly<FeatureFlags> = Object.freeze({
  enableClaudeSdk: true,
  enableCopilotSdk: true,
  enableExperimentalFeatures: false,
  prScoresAiReview: false,
  showAgentSelection: false,
  showBackstageExplorer: false,
  showBudgetLimits: false,
  showClearMemory: false,
  showComplianceLogs: false,
  showComposer: false,
  showConfigure: true,
  showCostTracking: false,
  showDashboard: true,
  showDataManagement: false,
  showEfficiencyCoach: false,
  showEnvVars: false,
  showExtensions: false,
  showHomeHub: true,
  showInsights: true,
  showIntegrations: false,
  showKnowledgeBase: false,
  showLearn: true,
  showMcpServers: false,
  showMemory: false,
  showPlugins: false,
  showPolicies: false,
  showPrScores: false,
  showScheduler: false,
  showSessionWizard: false,
  showSettings: true,
  showSetupWizard: true,
  showSkillsManagement: false,
  showSubAgents: false,
  showTeamHub: false,
  showTemplates: false,
  showUseContext: false,
  showVoice: false,
  showWebhooks: false,
  showWork: true,
  showWorkspaces: false,
});

/**
 * When true, the runtime layer must treat BUILD_FLAGS as the absolute
 * floor *and* ceiling: stored overrides are ignored, presets are
 * inert, the Settings → Feature Flags page hides off-by-default flags
 * entirely. Set CLEARPATH_FLAGS_LOCKED=1 at generation/build time to
 * turn this on (used by the dev:preview / preview:locked scripts to
 * simulate an end-user with the features.json defaults frozen).
 */
export const BUILD_FLAGS_LOCKED = true as const;

export const FEATURE_FLAG_META: Readonly<Record<FeatureFlagKey, FeatureFlagMetadata>> = Object.freeze({
  enableClaudeSdk: { experimental: false, enabled: true, addedIn: "1.8.0" },
  enableCopilotSdk: { experimental: false, enabled: true, addedIn: "1.8.0" },
  enableExperimentalFeatures: { experimental: true, enabled: false, addedIn: "1.5.0" },
  prScoresAiReview: { experimental: true, enabled: false, addedIn: "1.5.0" },
  showAgentSelection: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showBackstageExplorer: { experimental: true, enabled: false, addedIn: "1.6.0" },
  showBudgetLimits: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showClearMemory: { experimental: true, enabled: false, addedIn: "1.7.0" },
  showComplianceLogs: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showComposer: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showConfigure: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showCostTracking: { experimental: true, enabled: false, addedIn: "1.0.0" },
  showDashboard: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showDataManagement: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showEfficiencyCoach: { experimental: true, enabled: false, addedIn: "1.6.0" },
  showEnvVars: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showExtensions: { experimental: true, enabled: false, addedIn: "1.9.0" },
  showHomeHub: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showInsights: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showIntegrations: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showKnowledgeBase: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showLearn: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showMcpServers: { experimental: true, enabled: false, addedIn: "1.9.0" },
  showMemory: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showPlugins: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showPolicies: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showPrScores: { experimental: true, enabled: false, addedIn: "1.5.0" },
  showScheduler: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showSessionWizard: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showSettings: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showSetupWizard: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showSkillsManagement: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showSubAgents: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showTeamHub: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showTemplates: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showUseContext: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showVoice: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showWebhooks: { experimental: false, enabled: false, addedIn: "1.0.0" },
  showWork: { experimental: false, enabled: true, addedIn: "1.0.0" },
  showWorkspaces: { experimental: false, enabled: false, addedIn: "1.0.0" },
});

export const EXPERIMENTAL_FLAG_KEYS: readonly FeatureFlagKey[] = Object.freeze([
  'enableExperimentalFeatures',
  'prScoresAiReview',
  'showBackstageExplorer',
  'showClearMemory',
  'showCostTracking',
  'showEfficiencyCoach',
  'showExtensions',
  'showMcpServers',
  'showPrScores',
]);

export const FEATURE_FLAG_KEYS: readonly FeatureFlagKey[] = Object.freeze([
  'enableClaudeSdk',
  'enableCopilotSdk',
  'enableExperimentalFeatures',
  'prScoresAiReview',
  'showAgentSelection',
  'showBackstageExplorer',
  'showBudgetLimits',
  'showClearMemory',
  'showComplianceLogs',
  'showComposer',
  'showConfigure',
  'showCostTracking',
  'showDashboard',
  'showDataManagement',
  'showEfficiencyCoach',
  'showEnvVars',
  'showExtensions',
  'showHomeHub',
  'showInsights',
  'showIntegrations',
  'showKnowledgeBase',
  'showLearn',
  'showMcpServers',
  'showMemory',
  'showPlugins',
  'showPolicies',
  'showPrScores',
  'showScheduler',
  'showSessionWizard',
  'showSettings',
  'showSetupWizard',
  'showSkillsManagement',
  'showSubAgents',
  'showTeamHub',
  'showTemplates',
  'showUseContext',
  'showVoice',
  'showWebhooks',
  'showWork',
  'showWorkspaces',
]);

export function isExperimentalFlag(key: FeatureFlagKey): boolean {
  return FEATURE_FLAG_META[key].experimental;
}

/**
 * Read the build-time default for a flag by key. `__FEATURES__` is a Vite
 * `define` constant object (see electron.vite.config.ts), but this helper
 * does a *computed* property lookup with a runtime key argument — Rollup
 * can't constant-fold that, so this function does NOT participate in
 * tree-shaking. Use direct property access (`__FEATURES__.showPrScores`)
 * for tree-shaking-sensitive gates; reach for this helper only when the
 * key isn't known until runtime (e.g. iterating EXPERIMENTAL_FLAG_KEYS).
 *
 * For non-experimental flags this returns the BUILD_FLAGS default; the
 * runtime FeatureFlagContext / featureFlagHandlers layer per-user
 * overrides on top of that.
 */
declare const __FEATURES__: Readonly<FeatureFlags>;
export function isExperimentalFlagEnabledAtBuild(key: FeatureFlagKey): boolean {
  // eslint-disable-next-line no-restricted-globals
  return Boolean(__FEATURES__[key]);
}

export const FEATURE_SOURCE_VERSION = 1 as const;
